# Generated by Django 5.2 on 2025-12-05 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='claim',
            name='claim_type',
            field=models.CharField(choices=[('ACCIDENT', 'Accident'), ('THEFT', 'Theft'), ('DAMAGE', 'Damage'), ('OTHER', 'Other')], default='OTHER', max_length=16),
        ),
    ]
